//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public Barang()
        {
            this.ItemBelis = new HashSet<ItemBeli>();
        }
    
        public string BarangID { get; set; }
        public string NamaBarang { get; set; }
        public Nullable<int> HargaBeli { get; set; }
        public Nullable<int> HargaJual { get; set; }
        public string Stok { get; set; }
    
        public virtual ICollection<ItemBeli> ItemBelis { get; set; }
    }
}
