//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Belis = new HashSet<Beli>();
        }
    
        public int SupplierID { get; set; }
        public string NamaSupplier { get; set; }
        public string Jalan { get; set; }
        public string Kota { get; set; }
    
        public virtual ICollection<Beli> Belis { get; set; }
    }
}
